[Docs] Added advanced concurrency limits section
VapiAI/docs pull request #110
Opened 2024-12-12 05:19 UTC by ram-sharma

Add new section under Advanced Concepts > Managing Concurrency Limits

2024-12-12 12:57 UTC, sahilsuman933 commented
Not sure what the purpose of this documentation is. It would have been great if you could explain what concurrency is, the errors we might encounter, how we can add additional concurrency, and other generally asked questions.﻿

2024-12-12 13:01 UTC, sahilsuman933 requested changes
Tackle the following questions in this article:


1. What is concurrency? Explain how the concurrency limit is applied on the organization level, not on the phone number or assistant level.
2. What happens when the concurrency limit is exceeded?
3. How can we check the concurrency lines? (We don't expose it at the moment, but mention it.)
4. How to implement a queue system for the concurrency part.
5. How to purchase extra concurrency lines.

2024-12-12 20:44 UTC, ram-sharma commented
Discussed this with @sahilsuman933 , he mentioned that I made the changes he mentioned, removed reference to Subscription schema. The only part that is not included is implementing a queue system for the concurrent calls, that will probably be it's own advanced guide and will require a detailed write-up. 

[y] What is concurrency? Explain how the concurrency limit is applied on the organization level, not on the phone number or assistant level.
[y] What happens when the concurrency limit is exceeded?
[y] How can we check the concurrency lines? (We don't expose it at the moment, but mention it.)
[n] How to implement a queue system for the concurrency part.
[y] How to purchase extra concurrency lines.

2024-12-12 21:00 UTC, sahilsuman933 reviewed
Still, there are a lot of confusing things in this documentation, and it should be kind of straightforward.﻿

2024-12-12 21:01 UTC, sahilsuman933 requested changes
I'm uncertain about the sections on Managing Concurrency Effectively and the approach to handling retries﻿

2024-12-12 21:06 UTC, sahilsuman933 commented
Dumping some messages I replied to related to concurrency part:

```
Max number of concurrent calls that can be made in real-time. You can think of it with call centre analogy like one support person can talk to one client at a time when he is done then only he can talk to another person.

To increase the concurrency limit, you can do it via add-on plan which can be found under billing section.
```

```
it is for both inbound + outbound and we don’t have a queue mechanism incase of you hit the call concurrency limit. Although, there is a thing in twilio flex through which you can create this flow.
```

2025-01-01 15:01 UTC, sahilsuman933 commented
Closing this PR due to lack of activity.

2025-01-01 15:01 UTC, closed without merging